### ISSUE TITLE
Something isn't right with system.fps in lua

### ISSUE THREAD

**Issue by Skaruts** [pmgl/microstudio#160]
[This project](https://microstudio.io/i/Skaruts/microlifelua/) runs very slow, but `system.fps` still displays ~`60` fps:

![microlifelua](https://user-images.githubusercontent.com/6277234/189108763-1b5a3aa4-b98f-4f6b-a4e4-1e63c31bf4f2.png)

I also have this [same project in microScript](https://microstudio.io/i/Skaruts/microlife/), and there it displays the fps correctly.

**Comment by pmgl** [comment]
`system.fps` is a measure of how often the engine manages to call your function `draw` ; depending on the language engine inner workings, especially when the expected computation exceeds the allowed time slice (1/60 of a second), there can be some differences in the value you get. I am just guessing that the Lua engine works with shorter time slices and tries to give back control more often, while the microScript engine tries to not interrupt the main thread provided it doesn't exceed a few frames.

Also microScript in the browser is much faster than Lua in the browser. This is not inherent to Lua though, Lua can be extremely fast when you are using a native interpreter with LuaJIT. microScript has a big advantage in the browser because choices were made from the start to allow quick execution in JavaScript (and yet the transpiler isn't even activated in the current version!).
