### ISSUE TITLE
Animate animated-tiles in maps ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [pmgl/microstudio#51]
Hello again !

My map contains animated tiles. 
But when the map is displayed, these tiles are not animated.

I tried to add a `maps["myMap"].update()`, but no success.

Bug or missing-feature ?

**Comment by pmgl** [comment]
There is no such feature for now. I have considered this idea in the past. Maps are pre-rendered to a buffer and was thinking to achieve animation by having as many buffers as there are animation frames. The problem is that in the same map you may be using different sprites with different frame rates or different number of frames, which makes the whole approach much more complicated. Maybe I should rethink this, make maps only partially pre-rendered (static tiles only) and paint the few animated tiles on top of it. That would work fine, provided the map is not a 100x100 grid filled with only animated sprites!
